---
apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: learn-bad
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
      generateName: sum-and-multiply-pipeline-run-
      spec:
      pipelineRef:
        name: sum-and-multiply-pipeline
      params:
        - name: a
          value: "2"
        - name: b
          value: "10"

---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: learn-bad
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: learn-bad
spec:
  triggers:
    - binding:
        name: learn-bad
      template:
        name: learn-bad
