apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: matrix-include-task
  annotations:
    description: |
      A task that echoes image and dockerfile
spec:
  params:
    - name: IMAGE
    - name: DOCKERFILE
  steps:
    - name: echo
      image: alpine
      script: |
        echo "$(params.IMAGE) and $(params.DOCKERFILE)"
---

apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: matrix-include-pipeline-template
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        generateName: matrix-explicit-combos-
      spec:
        pipelineSpec:
          tasks:
            - name: matrix-include
              matrix:
                include:
                  - name: build-1
                    params:
                      - name: IMAGE
                        value: image-1
                      - name: DOCKERFILE
                        value: path/to/Dockerfile1
                  - name: build-2
                    params:
                      - name: IMAGE
                        value: image-2
                      - name: DOCKERFILE
                        value: path/to/Dockerfile2
                  - name: build-3
                    params:
                      - name: IMAGE
                        value: image-3
                      - name: DOCKERFILE
                        value: path/to/Dockerfile3
              taskRef:
                name: matrix-include-task
            - name: matrix-include-taskspec
              matrix:
                include:
                  - name: build-1
                    params:
                      - name: IMAGE
                        value: image-1
                      - name: DOCKERFILE
                        value: path/to/Dockerfile1
                  - name: build-2
                    params:
                      - name: IMAGE
                        value: image-2
                      - name: DOCKERFILE
                        value: path/to/Dockerfile2
                  - name: build-3
                    params:
                      - name: IMAGE
                        value: image-3
                      - name: DOCKERFILE
                        value: path/to/Dockerfile3
              taskSpec:
                params:
                  - name: IMAGE
                  - name: DOCKERFILE
                steps:
                  - name: echo
                    image: alpine
                    script: |
                      echo "$(params.IMAGE) and $(params.DOCKERFILE)"
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: manual-matrix-include-pipeline-binding
spec:
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: manual-matrix-include-listener
spec:
  triggers:
    - binding:
        name: manual-matrix-include-pipeline-binding
      template:
        name: matrix-include-pipeline-template
