apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: cancelled-running-finally-pipeline-template
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipelinerun-with-taskspec-to-echo-good-morning
      spec:
        pipelineSpec:
          tasks:
            - name: echo-good-morning
              taskSpec:
                metadata:
                  labels:
                    app: "example"
                steps:
                  - name: echo
                    image: ubuntu
                    script: |
                      #!/usr/bin/env bash
                      echo "Good Morning!"
                      sleep 10m
          finally:
            - name: cleanup
              taskSpec:
                step:
                  - name: echo
                    image: ubuntu
                    script: |
                      #!/usr/bin/env bash
                      echo "Goodbye!"
                      sleep 10m
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: manual-cancelled-running-finally-pipeline-binding
spec:
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: manual-cancelled-running-finally-listener
spec:
  triggers:
    - binding:
        name: manual-cancelled-running-finally-pipeline-binding
      template:
        name: cancelled-running-finally-pipeline-template
