apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: bad-image-pipeline-template
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipelinerun-with-taskspec-to-echo-good-morning
      spec:
        pipelineSpec:
          tasks:
            - name: echo-good-morning
              taskSpec:
                metadata:
                  labels:
                    app: "example"
                steps:
                  - name: echo
                    image: thisimagedoesnotexist
                    script: |
                      #!/usr/bin/env bash
                      echo "Good Morning!"
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: manual-bad-image-pipeline-binding
spec:
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: manual-bad-image-listener
spec:
  triggers:
    - binding:
        name: manual-bad-image-pipeline-binding
      template:
        name: bad-image-pipeline-template
