apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: inline-invalid-pipeline-template
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        name: pipelinerun-with-taskspec-to-echo-good-morning
      spec:
        PipelineSpec:
          task:
            - name: echo-good-morning
              taskSpec:
                metadata:
                  labels:
                    app: "example"
                steps:
                  - name: echo
                    image: ubuntu
                    script: |
                      #!/usr/bin/env bash
                      echo "Good Morning!"
                      echo "Shouldn't see this as the webhook should block the invalid spec"
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: manual-inline-invalid-pipeline-binding
spec:
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: manual-inline-invalid-listener
spec:
  triggers:
    - binding:
        name: manual-inline-invalid-pipeline-binding
      template:
        name: inline-invalid-pipeline-template
