apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: matrix-pipeline-template
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        generateName: matrixed-pr-with-retries-
      spec:
        pipelineSpec:
          tasks:
            - name: matrix-and-params-very-long-name-to-see-when-name-generated
              retries: 3
              params:
                - name: pipelineTask-retries
                  value: $(context.pipelineTask.retries)
                - name: browser
                  value: chrome
              matrix:
                params:
                  - name: platform
                    value:
                      - linux
                      - mac
                      - windows
              taskSpec:
                params:
                  - name: platform
                  - name: browser
                  - name: pipelineTask-retries
                steps:
                  - name: echo
                    image: alpine
                    script: |
                      #!/usr/bin/env sh
                      echo "$(params.platform) and $(params.browser)"

                      if [ "$(context.task.retry-count)" == "$(params.pipelineTask-retries)" ]; then
                        echo "This is the last retry."
                        exit 0
                      fi
                      echo "The PipelineTask has retried $(context.task.retry-count) times."
                      exit 1
            - name: always-fail
              retries: 1
              params:
                - name: browser
                  value: chrome
              matrix:
                params:
                  - name: platform
                    value:
                      - linux
                      - mac
                      - windows
              taskSpec:
                params:
                  - name: platform
                  - name: browser
                steps:
                  - name: echo
                    image: alpine
                    script: |
                      #!/usr/bin/env sh
                      echo "$(params.platform) and $(params.browser)"

                      exit 1
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: manual-matrix-pipeline-binding
spec:
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: manual-matrix-listener
spec:
  triggers:
    - binding:
        name: manual-matrix-pipeline-binding
      template:
        name: matrix-pipeline-template
